version: "3"
services:
  app:
    logging:
      driver: none
  worker:
    logging:
      driver: none
  tests:
    build:
      context: .
      dockerfile: tests.Dockerfile
    depends_on:
      - common
      - app
      - worker
      - mongo
      - redis
