version: "3"
services:
  common:
    image: pith-api_common:latest
    build:
      context: .
      dockerfile: ./dockerfiles/common.Dockerfile
  app:
    build:
      context: .
      dockerfile: ./dockerfiles/app.Dockerfile
    depends_on:
      - common
      - mongo
      - redis
    ports:
      - "5000-5001:8080"
    restart: always
    environment:
      MONGODB_CONN: ${MONGO}
      MONGODB_NAME: ${MONGO_NAME}
      REDIS_IP: ${REDIS}
    working_dir: /api
    volumes:
      - ./src:/api:cached
  worker:
    build:
      context: .
      dockerfile: ./dockerfiles/worker.Dockerfile
    depends_on:
      - app
      - common
      - mongo
      - redis
    restart: always
    environment:
      MONGODB_CONN: ${MONGO}
      MONGODB_NAME: ${MONGO_NAME}
      REDIS_IP: ${REDIS}
    working_dir: /api
    volumes:
      - ./src:/api:cached
  static:
    build:
      context: .
      dockerfile: ./dockerfiles/static.prod.Dockerfile
    restart: always
    depends_on:
      - app
    working_dir: /static
    ports:
      - "3000:3000"
    stdin_open: true
    environment:
      REACT_APP_BACKEND_HOST: ${HOST_NAME}
      REACT_APP_BACKEND_PORT: ${HOST_PORT}/api
    volumes:
      - ./frontend:/static:cached
  redis:
    image: "redis:alpine"
    restart: always
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
  balancer:
    build:
      context: .
      dockerfile: ./dockerfiles/balancer.Dockerfile
    depends_on:
      - app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    network_mode: "host"
