version: "3"
services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - worker
      - mongo
      - redis
    ports:
      - "8080:8080"
    restart: always
    environment:
      MONGODB_CONN: mongodb+srv://dbUser:XwgmOHe0WNkQ87YN@cluster0.nvpuq.mongodb.net/pith?retryWrites=true&w=majority
      REDIS_IP: redis
  worker:
    build:
      context: .
      dockerfile: worker.Dockerfile
    depends_on:
      - mongo
      - redis
    restart: always
    environment:
      MONGODB_CONN: mongodb+srv://dbUser:XwgmOHe0WNkQ87YN@cluster0.nvpuq.mongodb.net/pith?retryWrites=true&w=majority
      REDIS_IP: redis
  redis:
    image: "redis:alpine"
    logging:
      driver: none
    restart: always
  mongo:
    image: mongo
    restart: always
    logging:
      driver: none
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbUser
      MONGO_INITDB_ROOT_PASSWORD: XwgmOHe0WNkQ87YN
