version: "3"
services:
  app:
    logging:
      driver: none
  worker:
    logging:
      driver: none
  tests:
    build:
      context: .
      dockerfile: tests.Dockerfile
    depends_on:
      - common
      - app
      - worker
      - mongo
      - redis
    environment:
      MONGODB_CONN: ${MONGO}
      MONGODB_NAME: ${MONGO_NAME}
      REDIS_IP: ${REDIS}
